# Build a Qt project on macOS
name: Build on macOS

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          target: 'desktop'
          modules: 'gui core serialport network opengl xml'

      - name: Run qmake
        run: qmake .

      - name: Build with make
        run: make

      - name: Run make check
        run: make check

      # Uncomment the line below if you want to perform a distcheck
      # - name: Run make distcheck
      #   run: make distcheck
